### ISSUE TITLE
Ignores volume key framing in Blender 2.80

### ISSUE THREAD

**Issue by ghost** [mikeycal/the-video-editors-render-script-for-blender#15]
Hey Mikey

I just started using your script with Blender 2.80, but it seems to have issues with the volume of an audio strip that I've applied key frames to. This problem didn't exist when I've been using your script with earlier versions of Blender. It worked fine and respected my volume adjustments.

In my testing, it doesn't seem to matter what volumes I key frame, the script will ignore the changes made via key frames and the final version will be rendered at whatever volume the audio strip is set at on the audio strip's last frame.

I noticed the problem when rendering out some videos. To narrow down the problem, I tried rendering my video inside Blender 2.8 and the audio's key framed volume was working as intended. Narrowing down the problem to something related to the script.

I then created a new Blender file from scratch with a different video to see if it was an issue with the file.

- On frame 1, I set the volume of the audio strip to 0.5
- On frame 300, I set the volume to 1
- On frame 600, I set the audio to 0

When rendered the video using your plug-in, the video rendered fine, and fast, but there was no audio. 

I modified the blend file and set the volume on frame 600 to 2 and re-rendered using your script. The audio was now present and loud throughout. It didn't start on 0.5, nor did it increase and decrease over the course of the video, as I was expecting it to.

This lead me to the conclusion that the script doesn't consider volume changes when done with key frames.

I'm not sure if this problem is something only I'm having, but I thought I'd report it any way, to see if you're having similar issues.

Many thanks!

**Comment by mikeycal** [comment]
The script uses the Mixdown feature of Blender to create the Full project Audio file with keyframed volume. 
 
I have noticed that the official Mixdown feature in 2.8 seems to be acting odd. You may have found a blender bug. Test the mixdown feature in blender by setting up your project audio, go to Render Menu --> Render Audio. On the left side, set the Container to "wav" and Format to "F32" and save as 1.wav (This is exactly what the script is doing.) 

Does that give you the same result? If it does, you may have found a blender bug.  

I tried it and it seemed to be broken for me too. 


Source: 
https://docs.blender.org/api/current/bpy.ops.sound.html?highlight=bpy%20ops%20sound%20mixdown#bpy.ops.sound.mixdown

**Comment by mikeycal** [comment]
I am playing around with inserting keyframes into the Audio strip. I have noticed that if you insert a key frame by holding your mouse cursor over the volume setting and pressing  " i ", it seems to render, but if you click the insert keyframe icon on the right of the volume setting, it doesn't work -- this looks like a general blender bug.

**Comment by mikeycal** [comment]
I have officially reported this to the Blender Devs. Here is my bug report:
https://developer.blender.org/T69682

Feel free to add something to that report if you feel it is helpful. 

Since this is a blender issue, I am closing this problem report. Thanks .

**Comment by ghost** [comment]
Hey Mikeycal, thank you very much for figuring out what the problem was and also for reporting it, too.

I can confirm that when following your instructions (Render > Render Audio), the same problem occurs. So it looks like it is indeed a problem with Blender and not your script.

I was confused, because if I go to Render > Render Animation, there are no issues with the key framed audio. So I assumed it was something to do with your script. But I'm guessing that the audio is handled differently in that situation.

Hopefully the Blender devs can figure out a fix. Your awesome script has really improved my workflow over the years. Even more so since I upgraded my PC to a Ryzen 7. Thank you very much for everything.

**Comment by mikeycal** [comment]
I thought I would let you know that the blender audio keyframe issue -- that you brought to my attention -- has been elevated to "high priority" by the blender devs. I think that are trying to fix it by the 2.81 update. This is why reporting bugs is so important. Thanks for your help. :)

**Comment by mikeycal** [comment]
It looks like they actually fixed this issue, just today, in the nightly build for 2 .81.

Here's the official commit - fix:
https://developer.blender.org/rB6d3c34fe9d1eabc7765275ff68600734be0e3acb

**Comment by ghost** [comment]
Fantastic! Thank you very much for taking the effort to report it. It's great to see the issue not only addressed but fixed, too. Looking forward to using your plug in with 2.81 when it launched
