### ISSUE TITLE
There was an error compressing your audio. Please change your render settings.

### ISSUE THREAD

**Issue by marinesciencedude** [mikeycal/the-video-editors-render-script-for-blender#18]
Render Settings:

VIDEO: [ MPEG4 ( H264 ) ] [ 1920 x 1080 ] [ 23.98 FPS ] [ GOP 18 ]
        [ Quality: MEDIUM (GOOD)] [ Frames: 1 - 2568 ] [ Color Mode: RGB ]

  AUDIO: [ AAC ] [ 192 kb/s ] [ VOLUME: 100% ]
          [ Sample Rate: 48000 ] [ Audio Format: F32 ]

'Render Animation' in Blender works fine. Have tried AAC, AC3, FLAC, MP2, MP3, Opus, PCM, Vorbis with only PCM not receiving an error, though it didn't output a video file.

Log file for the PCM render:
[PCM_Renderlog.txt](https://github.com/mikeycal/the-video-editors-render-script-for-blender/files/4037070/PCM_Renderlog.txt)

**Comment by mikeycal** [comment]
Check to make sure that the file path to "FFmpeg" is set correctly.

**Comment by marinesciencedude** [comment]
FFmpeg file path is set correctly (and I have successfully rendered previous projects with this script so this shouldn't be a problem)

**Comment by mikeycal** [comment]
This may be related to an audio export bug that I reported to the blender devs a couple months ago. I thought they had fixed it, but it looks like it may still be an issue in 2.81a.

Basically, the Blender Audio export option sometimes doesn't work right -- in fact, I just tested it 3 times and it only worked 2 out 3 times that I tried it. This isn't a render script problem, it is a much bigger Blender audio export issue. I guess I can try re-report the problem. 

What you can try to do is, when you have started to render a project, go into the Working folder and try to play the Audio file that was exported. If it plays then it should render in the final video.

I'm surprised that I haven't noticed this issue until now, being that I have been rendering various project for weeks--without any issues.

**Comment by marinesciencedude** [comment]
Found some blank mp4 files numbered 2-8 and a playable 'Full_Audio.wav' file in Script_Working_Folder\AV_Source

No problems when using 'Render Audio' in Blender, though. Seems to just be an issue with audio compression during encoding.

**Comment by mikeycal** [comment]
There have been versions of ffmpeg that have had issues in the past -- try updating ffmpeg to the latest version to see if that helps. If you are able to generate a wav file that has working audio -- using the script -- than the issue may be with ffmpeg.

**Comment by marinesciencedude** [comment]
Updating ffmpeg did the trick.
