### ISSUE TITLE
If no audio you get an error message

### ISSUE THREAD

**Issue by gbarnabic** [mikeycal/the-video-editors-render-script-for-blender#4]
There may be a better way but if you add these lines after line 1059:

else:
    # this avoids the error message if no audio
    blender_audio_extract_time_end = time.time()

**Comment by mikeycal** [comment]
I'm having a hard time replicating this error. 
What platform are you seeing this error on? And what are your blender render settings? 

As far as I can see, blender_audio_extract_time should only be collected when 
blender_audio_codec != "NONE"

So it shouldn't display an error when there is no audio.

**Comment by gbarnabic** [comment]
You are correct the audio settings in Blender were not set to NONE.  What I did was drag a .mp4 file into blender and not change any of my default settings except for the dimensions of the video.  I then did a quick save to 1.blend and ran it per your instructions.  Since I didn't change the audio settings and there was no audio track in the original MP4 I'm guessing that the command line Blender instance didn't pick up  on the fact that there was no audio track.  The video was created it just showed the error because the blender_audio_extract_time was never declared because it never went into the Python audio code.  If you wanted to bullet proof the Python code you could also declare that variable outside of the audio if statement.  Or add a bunch of try except logic to catch things like that.  That may be overkill for what this is being used for.  Not a big deal now that I know to set the Blender audio to NONE going forward.  Thanks for looking into it.  Oh, Windows 8.1, Blender 2.76b.

**Comment by mikeycal** [comment]
Can you download the latest version of the code and see if you can still replicate this problem?
Basically, the python code should check to see if there are any audio strips in the project. If none are present, it should automatically reset the audio codec to "NONE" and avoid that error. 
I am testing on Windows 10 and getting no Errors with Blender 2.78C and FFmpeg 3.3. 
I wonder if there is something different with version of Python that comes with blender 2.76b vs 2.78C. That could be the cause of the problem.

**Comment by gbarnabic** [comment]
The lastest does not give me the error.  I saw that you added the if statement, (if blender_audio_codec != "NONE":) which I think is a better solution than the one I hacked together. Since the code to set the blender_audio_extact_time_end never gets called, when you do the math to figure out the time that uses that variable, the error occured because it was never declared.

Bottom line your latest change did fix the issue.
 
Two other very minor things: 
1. Your instructions say the .py file is called video_editors_render_script.py but the downloaded version adds the _v1.  It took me a minute to realize that since the initial command line string is so long.
2. Line 1224 typo MUX should be MIX (I told you it was minor!!)

Thanks for this.  I should come in handy for larger longer renders.

**Comment by mikeycal** [comment]
Mux is reference to Multiplexing: https://en.wikipedia.org/wiki/Multiplexer 
It's what we call it when we take audio and video steams and put them into a single file. 
For example we mux AAC audio codec and H.264 video codec together into a MP4 container. 

Thanks for your help :)
