### ISSUE TITLE
Broken Audio

### ISSUE THREAD

**Issue by hollunder** [mikeycal/the-video-editors-render-script-for-blender#7]
I've tested this script on one of my files. A Video of about 3:45 length with two audio tracks. I've done only a little cutting and audio/video fades.
The Script managed to render it in about 56 minutes but when I checked the file I found that the audio was broken starting at minute 32.

blender 17:2.78.c
ffmpeg version 3.3.3 on Linux x86_64

I'll try again tomorrow.

**Comment by mikeycal** [comment]
The script renders the Audio first and places the the audio file in the following folder:
Script_Working_Folder\AV_source\Full_Audio.* (WAV and M4A, or MP3)

When starting the script, after the Audio is converted, check to see if the Full_Audio.* files lose audio at 32 minutes in either audio file. 

If the WAV file is fine, then the issue is with FFMPEG.
If the M4A or MP3 file is fine, then the issue may be with the FFMPEG muxing operation that happens at the very end of the script.

If there is an issue with the muxing operation, I would simply try using a different version of FFmpeg.

**Comment by hollunder** [comment]
Hi mikeycal. Thanks for the fast response.

I think I've found the problem.

```
$ sndfile-info Full_Audio.wav 
========================================
File : Full_Audio.wav
Length : 5039257760
Warning : filelength > 0xffffffff. This is bad!!!!
RIFF : 744290456
WAVE
fmt  : 16
  Format        : 0x3 => WAVE_FORMAT_IEEE_FLOAT
  Channels      : 2
  Sample Rate   : 48000
  Block Align   : 8
  Bit Width     : 32
  Bytes/sec     : 384000
fact : 4
  frames  : 629907209
PEAK : 24
  version    : 1
  time stamp : 1503903517
    Ch   Position       Value
     0   4879880        1
     1   4879880        1
data : 744290376
*** Unknown chunk marker (BD0F9A90) at position 744290464. Exiting parser.

----------------------------------------
Sample Rate : 48000
Frames      : 93036297
Channels    : 2
Format      : 0x00010006
Sections    : 1
Seekable    : TRUE
Duration    : 00:32:18.256
Signal Max  : 1 (0.00 dB)
```

The audio file is too long for the WAV format to handle. The file size header overflows, resulting in a wrong length 32 minutes.

I see two solutions to this:
1) Use BWF or RF64 which are designed for larger files.
2) Keep using WAV and split large files.

I think 1) would be more sensible.

**Comment by hollunder** [comment]
Oh dear, seems like blender does not directly support any of those: https://docs.blender.org/api/blender_python_api_2_78c_release/bpy.ops.sound.html?highlight=bpy%20ops%20sound%20mixdown#bpy.ops.sound.mixdown

Maybe we can ask them to add one of those?

One workaround would be to mixdown to FLAC and go from there. One obvious issue is that FLAC can not do floating point audio.

**Comment by hollunder** [comment]
I've worked around this issue for now by specifying
export_audio_format = "S16"

This way the 3h30 file is 2.3 GB, well below the limit. This way the limit should be around the 6 hour mark.

**Comment by hollunder** [comment]
Come to think of it, blender shouldn't have created this illegal WAV file in the first place.
If you happen to have an account there already, can you report this as a bug and suggest they implement RF64 or somesuch?

**Comment by NathanLovato** [comment]
16bits wav is a good default - that's CD quality. Although Blender provides the option, you should never need more than 24. That's what we use for audio production, most of the time. But you can't hear the difference with 16bit audio unless you process the heck out of the track.

I'm not sure there's a maintainer for the sequencer today, but it seems to me it's a larger issue than just the audio: Blender doesn't seem to work well with long videos. Fellow youtuber Borodante told me he's had issues with hour+ long videos going out of sync over time, not talking about the rendering times. Even with a few blender instances running in //, you still often need the separate mixdown, and to re-encode everything at the end.

**Comment by hollunder** [comment]
The default atm. is something else, but 16 bit int is fine indeed, especially for the final mixdown. It seems like the script may adjust the volume afterwards, but that part of the script is hard to read (look for fix_volume). I think it's a call to ffmpeg, but I haven't looked at the details yet.

Blender is also not made for editing of long files. I can't even zoom out far enough to see the entire thing and moving the viewport around isn't that easy (or I just don't know how to do that efficiently yet). I still have plenty of videos to watch :)

**Comment by mikeycal** [comment]
The script only alters the volume if the master volume is changed from the default of 1.0 (100% volume) to something else.

The script has blender do all video rendering, while the external FFmpeg is responsible for audio alteration, audio transcoding and final audio/video muxing. Having said that, blender is used for the initial PCM audio export. If the setting is available to blender's audio export feature, the script can be altered to use the setting. 

When it comes to audio losing sync when a video is really long. This shouldn't happen when using this script. The reason why audio is exported and muxed the way that this script does it, is to prevent audio sync issues. While the video is broken into pieces to speed up rendering, project audio is mixed down and exported as a single PCM audio file and muxed with the joined video files at the end of the script. This process should eliminate any audio shift.

**Comment by hollunder** [comment]
Where would that volume be changed? Do you mean within the blender project? If so then blender should take care of that (e.g. normalize it to 1.0) while downmixing. Or is there some other operation in there that might screw with the volume?

**Comment by mikeycal** [comment]
In blender, there is a difference between rendering audio and exporting it with the API. The API export process, that is used with this script, doesn't support master volume settings directly. This meant that I had to alter volume after the mixdown process had finished. This is just another way that blender is inconsistent.  :(

**Comment by NathanLovato** [comment]
Ah sorry Mike, my comment wasn't related to your script - it's a more general issue the lad's had about Blender. And I've had to write a few hacks over time on my video editing add-on too, for different reasons (e.g. had a bug with Blender thinking a specific video had a framerate > 120, while it was the same as all the others, 24, recorded the same way, and they all worked fine). Anyway, thanks for the info :)

**Comment by mikeycal** [comment]
Having said that, blender occasionally makes changes to the API. I noticed that they have changed the render option a little in 2.79 to accommodate for the new constant quality render settings
